### ISSUE TITLE
申請 intl@g0v.tw 信箱

### ISSUE THREAD

**Issue by pm5** [g0v/domain#24]
申請 intl@g0v.tw 信箱，轉信到 g0v-intl@googlegroups.com。

**Comment by wildjcrt** [comment]
+1 
@ronnywang 不過這是 g0v domain 在做的事情嗎？ XD

**Comment by ronnywang** [comment]
+1 
不過這好像不是 g0v domain 的東西 XDDDDD

**Comment by pm5** [comment]
那這個應該 cue 哪裡呢？...

**Comment by ronnywang** [comment]
目前 @g0v.tw 是用 mailgun 管理的，帳號好像只有 @clkao 有權限。這週五揪松會議會提出來討論 
https://trello.com/c/c30KqBe0/1521-%E7%94%B3%E8%AB%8B-g0vtw-%E8%BD%89%E4%BF%A1%E6%B5%81%E7%A8%8B

**Comment by chihaoyo** [comment]
@g0v.tw 列入《社群治理流程綜合討論》
https://g0v.hackmd.io/vYdTfaYeR7SnIU3zT5evOw?both#g0vtw-email

**Comment by ronnywang** [comment]
根據在 https://g0v-slack-archive.g0v.ronny.tw/index/channel/CF3JH3H1C/2019-04 g0v-domain team 的投票結果，目前 @g0v.tw 轉信也由 domain team 管理，並且要求要符合四項規範才會轉信
1. 只能轉信給群組
2. 群組需與g0v社群有關
3. 有公開治理機制
4.群組成員名單需公開

請 @pm5 再協助提供 1. 公開治理機制文件共筆 (放 hackmd 或是 hackpad 上？）  2. 共筆內需包含現有成員名單

謝謝

**Comment by pm5** [comment]
@ronnywang：

1. [公開治理機制文件](https://g0v.hackmd.io/Ozy9SKwORXOIBFiGdSkLtw?both)
2. 文件內有目前成員：isabel, pm5, chihao, ipa

**Comment by ronnywang** [comment]
ok, 這邊現在沒自動機制，先請 clkao 協助手動設定 XD

**Comment by clkao** [comment]
done!
