### ISSUE TITLE
申請幫 hack.g0v.tw 加上 jothon.g0v.tw 網域

### ISSUE THREAD

**Issue by ronnywang** [g0v/domain#27]
考量到 hack 這詞對有些新參者來講會有點「恐怖」，以及增加 jothon 的識別
揪松這邊想申請將原先的 hack.g0v.tw 再增加 jothon.g0v.tw ，讓兩個 domain 都可以連到同一頁
並且幫原來的 hack.g0v.tw 補上 repository 和 maintainer 設定

domain: hack.g0v.tw, jothon.g0v.tw
A: 35.197.156.202
repository: https://github.com/g0v/jothon-net
maintainer: tkirby

**Comment by ronnywang** [comment]
https://trello.com/c/MCHlLcnY/1576-%E8%A8%8E%E8%AB%96-jothong0vtw-%E6%88%90%E7%82%BA%E6%8F%AA%E6%9D%BE%E4%B8%BB%E7%B6%B2%E5%9F%9F

在揪松討論的卡

**Comment by wildjcrt** [comment]
+1

**Comment by zbryikt** [comment]
+1

**Comment by caasi** [comment]
+1

**Comment by ronnywang** [comment]
超過 +2 了，那我來執行囉

**Comment by ronnywang** [comment]
設好了，確認 48hr 內 http://jothon.g0v.tw/ 有生效並且有 https 再關票

**Comment by ronnywang** [comment]
結果發現 github page 一個 repository 只能綁一個 domain
所以不能同時 jothon.g0v.tw 和 hack.g0v.tw 都綁到 https://github.com/g0v/jothon-net/ 上

所以這邊會改成 jothon.g0v.tw 指到 https://github.com/g0v/jothon-net/ ，並且 hack.g0v.tw 301 到 jothon.g0v.tw

**Comment by ronnywang** [comment]
變更如下：
hack.g0v.tw CNAME 301.ronny.tw
hack.g0v.tw TXT "https://jothon.g0v.tw/*"

**Comment by ronnywang** [comment]
好，設定完成了，幾個檢查如下：
1. https://jothon.g0v.tw/ 可以正常連到揪松網，並且 https 正常（github page)
2. https://hack.g0v.tw/ 可以正常 301 到 https://jothon.g0v.tw/ ，並且 https 也正常 (301.ronny.tw)
3. https://hack.g0v.tw/about 這樣的舊網址可以導到 https://jothon.g0v.tw/about

**Comment by ronnywang** [comment]
ok, 這張 issue 關掉
