### ISSUE TITLE
www.g0v.tw redirect issue

### ISSUE THREAD

**Issue by audreyt** [g0v/domain#32]
https://www.g0v.tw is not redirecting properly to https://g0v.tw — as reported by gemlog.ca over at https://libranet.de/display/0b6b25a8-105d-be68-d47c-597489995923

**Comment by ronnywang** [comment]
我提議用我做的 https://301.ronny.tw/ 服務，把 www.g0v.tw 301 到 g0v.tw
在 g0v domain 設定這邊，要加上 www.g0v.tw CNAME to 301.ronny.tw 和 TEXT to "301 g0v.tw"

根據 domain team policy ，再一個 domain team 成員 +1 就開始執行

**Comment by caasi** [comment]
+1

**Comment by wildjcrt** [comment]
這應該是一次性的，不能直接寫 CNAME www g0v.tw 就好了嗎？交給 https://301.ronny.tw/ 有什麼特別的好處？

**Comment by ronnywang** [comment]
因為 g0v.tw 目前是用 github page ,github page 一個 repository 只能綁一個 domain,所以要用 301
的方式

Jerry Lee <notifications@github.com> 於 2019年11月4日 週一 下午2:02 寫道：

**Comment by ronnywang** [comment]
我已經設定完成了， https://www.g0v.tw/ 可以轉到 https://g0v.tw/ 了
或小蟹這邊有沒有建議其他作法？如果有的話我再改掉

沒有的話就請 au 確認看看要不要關掉 issue 了

**Comment by wildjcrt** [comment]
slack 上跟 ronny 確認了我的想法不可行，所以就交給 @audreyt close 吧

ref: https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/td-p/7116
