### ISSUE TITLE
申請 tw.g0v.dev 網址

### ISSUE THREAD

**Issue by zbryikt** [g0v/domain#35]
主要維護人： @zbryikt
repository： https://github.com/g0v/landing-page
申請網域：tw.g0v.dev
目標網域：g0v.github.io

用途: 方便官網開發
官網上線後可改為支援台灣區開發者專頁 (?!)

**Comment by ronnywang** [comment]
+1

**Comment by kiang** [comment]
+1

**Comment by ronnywang** [comment]
ok, 兩人 +1 ，已更新 DNS 設定

**Comment by ronnywang** [comment]
@zbryikt  https://github.com/g0v/landing-page/settings 那邊的 CNAME 設定是不是要需要改一下？

**Comment by zbryikt** [comment]
已更新, 上線囉！ https://tw.g0v.dev
