### ISSUE TITLE
sch001.g0v.tw 申請轉址至 https://g0v.hackmd.io/@jothon/sch001

### ISSUE THREAD

**Issue by ronnywang** [g0v/domain#36]
揪松團在 2020 年有個專案是「零時小學校」（專案名稱 sch001），想要以黑客松形式建立開源的教育工具
專案網址在 https://g0v.hackmd.io/@jothon/sch001

想要申請透過 sch001.g0v.tw 轉址到 https://g0v.hackmd.io/@jothon/sch001

設定：
CNAME: 301.ronny.tw
TEXT: "301 https://g0v.hackmd.io/@jothon/sch001"

**Comment by ronnywang** [comment]
需要兩位 domain team 成員協助 ++ ，謝謝

**Comment by wildjcrt** [comment]
+1

**Comment by ronnywang** [comment]
我也是 domain team 成員，那我也 + 1 好了 XD

**Comment by ronnywang** [comment]
ok, 設定完成，https 也確認 ok 了
