### ISSUE TITLE
申請 @summit.g0v.tw 信箱

### ISSUE THREAD

**Issue by chihaoyo** [g0v/domain#38]
- host@summit.g0v.tw 轉信至 g0v-summit-host@googlegroups.com
- google group 目前成員 - pm5, chihao, bess, isabel, Howard, urda, delightfullychaotic
- summit WG 開放治理機制草案 - https://g0v.hackmd.io/c_mPhOsZQC6FHJiMl3BIhw

**Comment by wildjcrt** [comment]
+1

**Comment by ronnywang** [comment]
我先補個 +1 ，不過有技術問題正在 #g0v-domain 討論

**Comment by ronnywang** [comment]
https://github.com/g0v/domain/blob/master/g0v.tw/summit.g0v.tw.json#L42
前幾年 summit 用的轉信都有包含年份， Ex: service-2018, accounting-2018, partner-2018

@chihaoyo 要不要把 host@summit.g0v.tw 改成 host-2020@summit.g0v.tw ?

**Comment by ronnywang** [comment]
ok, 設定已經完成
請 @chihaoyo 協助看看是否有收到我寄出的測試信

**Comment by chihaoyo** [comment]
@ronnywang ++
經過總籌組討論，google groups 已更新命名為 `g0v-summit-2020-host@googlegroups.com，所以想麻煩 domain 小組更新設定

host@summit.g0v.tw 轉信至 g0v-summit-2020-host@googlegroups.com

**Comment by chihaoyo** [comment]
另外申請

finance@summit.g0v.tw 轉信至 g0v-summit-2020-finance@googlegroups.com

開放治理機制在同一個地方 https://g0v.hackmd.io/c_mPhOsZQC6FHJiMl3BIhw

**Comment by ronnywang** [comment]
剛發現 g0v-summit-2020-host 的部份， google 已經自動更新了
我這邊不需要做任何動作

不過剛剛仍寄了封信標題為「測試 host@summit.g0v.tw 轉信」
請 @chihaoyo 確認是否有收到，謝謝

**Comment by ronnywang** [comment]
finance@summit.g0v.tw 轉信至 g0v-summit-2020-finance@googlegroups.com 也設定完成

請 @chiahao 協助確認是否有收到測試信件

**Comment by ronnywang** [comment]
sorry 上個 comment tag 錯人
重新 tag @chihaoyo

**Comment by chihaoyo** [comment]
finance 測試中

**Comment by chihaoyo** [comment]
另外申請

programming@summit.g0v.tw 轉信至 g0v-summit-2020-programming@googlegroups.com

開放治理機制在同一個地方 https://g0v.hackmd.io/c_mPhOsZQC6FHJiMl3BIhw

**Comment by chihaoyo** [comment]
再申請 wg@summit.g0v.tw 轉信至 g0v-summit-2020-wg@googlegroups.com

開放治理機制在同一個地方 https://g0v.hackmd.io/c_mPhOsZQC6FHJiMl3BIhw

**Comment by wildjcrt** [comment]
這兩個 +1

1. programming@summit.g0v.tw 轉信至 g0v-summit-2020-programming@googlegroups.com
2. wg@summit.g0v.tw 轉信至 g0v-summit-2020-wg@googlegroups.com

**Comment by zbryikt** [comment]
同 https://github.com/g0v/domain/issues/38#issuecomment-663988032 +1

**Comment by ronnywang** [comment]
ok, 已經設定完成並寄出測試信件

請 @chihaoyo 協助確認是否有收到測試信件
謝謝

**Comment by pm5** [comment]
再申請 coc@summit.g0v.tw 轉信到 g0v-summit-2020-coc@googlegroups.com

治理機制在同一個地方 https://g0v.hackmd.io/c_mPhOsZQC6FHJiMl3BIhw

**Comment by ronnywang** [comment]
設定已完成，並寄了封測試信件
請 @pm5 協助確認是否有收到信件？

**Comment by pm5** [comment]
有收到信件。感謝

**Comment by pm5** [comment]
目前都有收到信件，我把 issue 關掉囉
