### ISSUE TITLE
申請 sch001.g0v.dev 網址

### ISSUE THREAD

**Issue by SeanGau** [g0v/domain#40]
主要維護人： @SeanGau 
repository： https://github.com/g0v/sch001-net
申請網域：sch001.g0v.dev
目標網域：g0v.github.io/sch001-net

**Comment by ronnywang** [comment]
+1

**Comment by ronnywang** [comment]
你是用 github page 還是會另外自行架起來呢？
如果是 github page 的話，那目標網域應該要設 CNAME g0v.github.io ，並且你的 repo 要有 CNAME 這個檔

如果你是自行架起來，那這邊可能要提供你自架的主機位置

**Comment by SeanGau** [comment]
目前是只有前端的部分，先留在Github上，等Kirby那邊Grantdash好了以後再看要架在哪~
目前是CNAME到我自己的網域，不過還是想說改用g0v.dev

**Comment by wildjcrt** [comment]
+1

**Comment by ronnywang** [comment]
ok, 設定完成了，再請 @SeanGau 設定 github page 的部份
另外 .dev 網域有被要求一定要 https ，所以也要憑證過了才能看的到內容喔

**Comment by ronnywang** [comment]
已確定 https://sch001.g0v.dev 可以連結到
這張 issue 關掉囉
