### ISSUE TITLE
申請轉址 sch001.g0v.tw 至 grantdash.io

### ISSUE THREAD

**Issue by SeanGau** [g0v/domain#44]
零時小學校的新版Grantdash要上線了！感謝Kirby讚嘆Kirby

主要維護人： @SeanGau @zbryikt 
repository： https://github.com/plotdb/grantdash
申請網域：sch001.g0v.tw
目標網域：grantdash.io

**Comment by wildjcrt** [comment]
+1

**Comment by ronnywang** [comment]
+1

**Comment by ronnywang** [comment]
已兩人 +1 通過，設定已變更

請 @SeanGau 於 48hr 內完成後續設定，確定該網址能成功被連上，否則將會將設定還原回去

**Comment by zbryikt** [comment]
@ronnywang 由於 grantdash.io 也在 cloudflare, cloudflare 似乎禁止 CNAME 這樣指定 ( 從 A 帳號透過 CNAME 指到 B 帳號的 domain )

目前看起來可能需要 grantdash.io 這邊升級帳號後聯絡 cloudflare 才行, 考慮到明天就要用, 做為 workaround, 能改為直接透過 A Record 指向 IP 嗎? IP 我私訊給你了

**Comment by ronnywang** [comment]
IP 34.80.243.157
可以直接寫在這邊 comment 上
不寫之後從 commit log 還是看的到

**Comment by zbryikt** [comment]
已經設定完成囉! https://sch001.g0v.tw

**Comment by ronnywang** [comment]
ok, 感謝
