### ISSUE TITLE
申請 dashboard.g0v.tw 網域

### ISSUE THREAD

**Issue by SeanGau** [g0v/domain#52]
覺得g0v dashboard一直用 雲林鄧先生437911 好像不太好，想直接給個網址！
前端頁面同步放置在 g0v.tw/dashboard

主要維護人： @SeanGau 
repository： https://github.com/g0v/g0v-dashboard
申請網域：dashboard.g0v.tw
目標網域：https://yunlin-teng-437911.middle2.me/

**Comment by ronnywang** [comment]
+1

**Comment by wildjcrt** [comment]
+1

**Comment by ronnywang** [comment]
ok, 兩人 +1 ，已經設定完成
因為是在 middle2 上， https 我也已經設定好了
再請 @SeanGau 設定好 middle2 上面的網域設定喔

**Comment by SeanGau** [comment]
感謝~
