### ISSUE TITLE
budget.g0v.tw 轉移到 middle2

### ISSUE THREAD

**Issue by ronnywang** [g0v/domain#53]
http://budget.g0v.tw/ 因為放在 Heroku 並使用 Heroku-16 ，但因為 Heroku-16 在 5/1 被[停用](https://help.heroku.com/0S5P41DC/heroku-16-end-of-life-faq)，現在已經無法使用。但我一直都無法在最新的 Heroku-20 把他 build 起來，因此決定把他搬到 middle2 上面

主要是把 CNAME 從 g0v-budget.herokuapp.com 改成 yilan-fan-487473.middle2.me，已經關掉在 #37 用的 cloudflare ssh

**Comment by ronnywang** [comment]
這個好像不需要 reviewer ++ ? 我本人是 budget.g0v.tw 的 maintainer 之一，那我就直接修改囉

**Comment by wildjcrt** [comment]
還是幫忙點個 +1
