### ISSUE TITLE
申請 timeline.g0v.tw

### ISSUE THREAD

**Issue by Stimim** [g0v/domain#65]
主要維護人： @Stimim 
repository：https://github.com/Stimim/g0v-timeline
domain：timeline.g0v.tw
申請通過後會將 gh-page 指向新的 domain

專案簡介：https://g0v.hackmd.io/6di30sFRRPyXmYVM6Er5tw

**Comment by ronnywang** [comment]
+1

**Comment by wildjcrt** [comment]
+1

**Comment by ronnywang** [comment]
好，湊滿兩人了，我來執行

**Comment by Stimim** [comment]
感謝，gh-page 已經設定完成。需要關掉這條 issue 嗎？

**Comment by ronnywang** [comment]
好的，確認有 https://timeline.g0v.tw/ 就可以 close 了
