### ISSUE TITLE
申請 summit2024.g0v.tw

### ISSUE THREAD

**Issue by SeanGau** [g0v/domain#67]
主要維護人： @SeanGau 
repository： https://github.com/g0v/summit2024
domain：summit2024.g0v.tw
指向: A record 指到 34.80.243.157

專案簡介：https://g0v.hackmd.io/@summit2024/book/

**Comment by zbryikt** [comment]
+1

**Comment by ronnywang** [comment]
+1

**Comment by ronnywang** [comment]
DNS 已設定完成，請在 72hr 內將 https 設定完成

**Comment by pm5** [comment]
這個已經在用了，應該沒有缺什麼，可以關掉了？

**Comment by SeanGau** [comment]
感謝~那我關囉
