### ISSUE TITLE
申請檔案庫 立委咖電喂（g0v domain repository）

### ISSUE THREAD

**Issue by FumiMiyabe** [g0v/domain#7]
主要聯絡人Fumi 
專案名稱 立委咖電喂
申請網域名稱 callliwei.g0v.tw
原網域網址 http://callliwei.hopto.org
原始資料Hackfoldr http://beta.hackfoldr.org/callliwei
這個網頁主要提供立委聯絡資訊讓民眾可以找到選區立委表達意見 
資料有github 完全是open source喔 https://github.com/zhengda/callliwei
目前不知道申請網域還需要哪些資料或遺漏的，或是步驟錯誤，懇請提出意見啊> <
g0v logo還沒加 但都有導回其他g0v專案 感謝！！！！！！！！！！

（須加掛 g0v 的 Google Analytics）>請問這一點是有加Google Analytics就好了嗎？？？？？？

**Comment by ronnywang** [comment]
麻煩請再補充幾件事
1. 請問新的 callliwei.g0v.tw 是要設定成 CNAME callliwei.hopto.org 還是 A 111.240.238.206
2. 請補一下 https://github.com/zhengda/callliwei 的 g0v.json ，關於 g0v.json 產生可以透過 https://g0v.github.io/editor/?repo=zhengda/calliwei g0v editor 生成

其他部分應該沒什麼問題，GA 現在先加自己的沒問題，目前規則還在討論中，等規則定案後需要再改會再通知您

**Comment by FumiMiyabe** [comment]
收到，感恩！

**Comment by zhengda** [comment]
1.目前service還是跑在動態IP下。我猜g0v.tw還是傳統DNS，所以domain設成CNAME callliwei.hopto.org比較好。
2. 有目前有掛我自己的GA。改用g0v的也OK，需要UA_ID。
3. 已用g0v editor建立g0v.json https://raw.githubusercontent.com/zhengda/callliwei/master/g0v.json

**Comment by FumiMiyabe** [comment]
Leonlin大感激！！！

**Comment by FumiMiyabe** [comment]
ronnywang請問目前這樣ＯＫ了嗎
（謝謝您數位藝術節簡報好像曾經想幫我調輸出喔）

**Comment by thewayiam** [comment]
因 domain 申請機制還沒定案，先幫留下主要聯絡人聯絡方式：
uriawang[at]gmail.com
g0v slack @fumi

另外如果未來沒有打算加入立法院以外的資料，要不要考慮多加個 ly 好分類：callliwei.g0v.tw => callliwei.ly.g0v.tw

**Comment by FumiMiyabe** [comment]
好的，Johnny，因為之前Leonlin也有提出討論過
那麼立委咖電喂的網址就改為callliwei.ly.g0v.tw 
以便加入立法院分類吧！

**Comment by zhengda** [comment]
補充：上次討論時有提到 call.ly.g0v.tw ，好記的網址很重要， callliwei我自己都常少打一個L。請Fumi評估一下。

**Comment by ronnywang** [comment]
目前這個 domain 申請提供的資訊都足以開 domain 了
我覺得 call.ly.g0v.tw 或是 callliwei.ly.g0v.tw 都可以，確實針對立院的專案用 ly.g0v.tw 比較好
請 @zhengda 和 @FumiMiyabe 選定一個吧? 確定的話我這邊就把他設定完成囉

**Comment by FumiMiyabe** [comment]
您好，就照 @zhengda 說的 call.ly.g0v.tw 簡單為上
反正都是打給立院的!!!!!!!!!
(callliwei只是保留glyn取的名稱)
謝謝 ^_____^

**Comment by ronnywang** [comment]
好，我現在來幫你設定

**Comment by FumiMiyabe** [comment]
謝謝 @ronnywang

**Comment by ronnywang** [comment]
設定完成囉，請 @FumiMiyabe 確認看看
現在 http://call.ly.g0v.tw/ 應該已經可以連了

沒問題的話請就幫我把這個 issue 關掉吧。
如果之後需要變更的話再開新的 issue 吧 :)

**Comment by FumiMiyabe** [comment]
連嫌完成
謝謝 @ronnywang  @thewayiam  @zhengda
