### ISSUE TITLE
g0v.us 指到 https://zbryikt.github.io/g0v.asia

### ISSUE THREAD

**Issue by ronnywang** [g0v/domain#70]
主要維護人： @zbryikt
repository： https://github.com/g0v/g0v.asia
domain：g0v.asia
指向: CNAME record 指到 g0v.github.io

主要幫 g0v.us 增加一個首頁，讓大家知道 g0v 是什麼，避免被誤認為是偽政府網站

**Comment by ronnywang** [comment]
+1

**Comment by wildjcrt** [comment]
+1

**Comment by zbryikt** [comment]
+1

**Comment by ronnywang** [comment]
現在 http://www.g0v.us 被 https://github.com/dwhuang/g0vus 佔走了，因此 www.g0v.us 連到的是 2014 美東黑客松的網頁
而不是剛設上的 g0v.asia

關於 g0v.us 的使用方式，目前我提議如下規劃：
- g0v.us => 顯示 https://zbryikt.github.io/g0v.asia 這一頁的資訊（@ky 提議可加入一個區塊放美國相關黑客松的連結）
- 2014dc.g0v.us => 本來的 2014 美東黑客松，現在 http://www.g0v.us 看到的頁面
- siliconvalley.g0v.us => 連到現在灣區黑客松的頁面

目前有在 g0v slack #g0v-sillconvalley 提案這點討論，目前應該沒什麼異議
想請 @wildjcrt 和 @zbryikt 再幫忙確認一下，是否同意上面的規劃
沒問題的話我就照這樣設定囉

**Comment by ronnywang** [comment]
另外關於 g0v.us 已經被 dwhuang/g0vus 佔走的事
可以透過 https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages 這邊搶回來

**Comment by wildjcrt** [comment]
- g0v.us => 顯示 https://zbryikt.github.io/g0v.asia 這一頁的資訊（@ky 提議可加入一個區塊放美國相關黑客松的連結） >> ok
- 2014dc.g0v.us => 本來的 2014 美東黑客松，現在 http://www.g0v.us/ 看到的頁面 >> ok
- siliconvalley.g0v.us => 連到現在灣區黑客松的頁面 >> ok

另外 [www.g0v.us](https://www.g0v.us/) 應該可以設定轉向去 [g0v.us](https://g0v.us/) ，以及看能不能都上 https。

https://zbryikt.github.io/g0v.asia 我會建議 @zbryikt 是不是能改 repo name 為 https://zbryikt.github.io/g0v.us ，以後比較不會混淆。

**Comment by ronnywang** [comment]
https://github.com/zbryikt/g0v.asia 的部份，我把他 fork 到 https://github.com/g0v/g0v.asia 了
想說之後設定到 g0v.github.io 的話，這樣子 g0v 社群的人都可以改
那這樣要不要把 https://github.com/g0v/g0v.asia 改名叫 g0v.us?

**Comment by wildjcrt** [comment]
> https://github.com/zbryikt/g0v.asia 的部份，我把他 fork 到 https://github.com/g0v/g0v.asia 了 想說之後設定到 g0v.github.io 的話，這樣子 g0v 社群的人都可以改 那這樣要不要把 https://github.com/g0v/g0v.asia 改名叫 g0v.us?

我覺得改比較好，不會混淆。
以後有需要再設定 g0v.asia 時，可以再 fork。

**Comment by ronnywang** [comment]
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages#verifying-a-domain-that-is-already-taken
來把 g0v.us 搶回來，看起來需要等七天

現在已經做的事如下：
1. 把 https://github.com/g0v/g0v.asia 改名成 https://github.com/g0v/g0v.us
2. 把 https://github.com/g0v/g0vus 改名成 https://github.com/g0v/2014dc.g0v.us ，並且已經指定 https://2014dc.g0v.us
至於 g0v.us 變更的部份，要等 github release 掉舊的 owner 才能改，因此要等七天

**Comment by ronnywang** [comment]
這部份都設定完成了，謝謝大家，關票囉
