### ISSUE TITLE
申請 awesome.g0v.tw

### ISSUE THREAD

**Issue by chunyenHuang** [g0v/domain#75]
主要維護人： @chunyenHuang @tinghuatseng
repository： https://github.com/chunyenHuang/awesome-g0v-projects
申請網址：[awesome.g0v.tw](http://awesome.g0v.tw/)
網頁預覽：https://chunyenhuang.github.io/awesome-g0v-projects/#/
目標cname：https://chunyenhuang.github.io/awesome-g0v-projects/#/
專案簡介：https://github.com/chunyenHuang/awesome-g0v-projects

**Comment by wildjcrt** [comment]
+1

**Comment by ronnywang** [comment]
+1

**Comment by ronnywang** [comment]
ok, 兩人 +1 ，我來設定

**Comment by ronnywang** [comment]
已經設定好 awesome.g0v.tw CNAME 到 chunyenhuang.github.io
麻煩 @chunyenHuang 在 48hr 內把 github page 設定設好喔

**Comment by chunyenHuang** [comment]
設定好了 感謝協助
