### ISSUE TITLE
申請新增 @summit.g0v.tw 轉信

### ISSUE THREAD

**Issue by pm5** [g0v/domain#76]
主要維護人：@pm5
群組內容：g0v Summit 2024 籌備團隊
專案簡介：https://g0v.hackmd.io/@summit2024/book/

申請信箱：[ticket@summit.g0v.tw](mailto:ticket@summit.g0v.tw) 轉址到 [g0v-summit-2024-ticketing@googlegroups.com](mailto:g0v-summit-2024-ticketing@googlegroups.com)

summit WG 開放治理機制草案 - https://g0v.hackmd.io/@summit2024/book/%2FhsRMnnIMRZyhWE9pw6n6fg

**Comment by wildjcrt** [comment]
+1

**Comment by ronnywang** [comment]
已設定完成

收到請跟我說（沒收到也請跟我說）

**Comment by ronnywang** [comment]
看來有收到了！
