### ISSUE TITLE
討論 airmap.g0v.tw 終止服務後之網域存廢

### ISSUE THREAD

**Issue by Lafudoci** [g0v/domain#84]
該網站目前的資料運作已故障，與填坑工程師討論後，認為本專案已經不需要再繼續維護，故主機將於月底停機。

原本打算是直接釋出網域，不過翻了前幾個issue，似乎這邊會建議轉為靜態頁面以供指路，但本專案有詳細共筆 

https://beta.hackfoldr.org/g0vairmap

個人覺得其實很容易google到就不一定要留原網域，還是這裡能做到轉址?

提出來看看有沒有想法或建議。

**Comment by ronnywang** [comment]
可以選擇轉址喔，目前我有開發 https://301.ronny.tw/ 可以直接 301 或 302 到特定網址

**Comment by Lafudoci** [comment]
@ronnywang 聽起來不錯，如果到月底沒有其他人提出意見，我們就來把它改成轉址到共筆吧，謝謝

**Comment by ronnywang** [comment]
ok, 已經完成，現在會轉址到 hackfoldr
https://airmap.g0v.tw
